# Generated by Django 2.0.2 on 2018-05-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_movie_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
